SELECT * FROM customer LIMIT 20;

-- q1. what is total revenue generated by male and female
SELECT gender, SUM("purchaseamount(usd)") AS revenue
FROM customer
GROUP BY gender;
--q2 which customers used a discount but still spent more than the average purchase amount??
SELECT customerid, "purchaseamount(usd)"
FROM customer
WHERE discountapplied = 'Yes' 
  AND "purchaseamount(usd)" >= (
        SELECT AVG("purchaseamount(usd)") 
        FROM customer
      );
--whiich are the top 5 product with the highest average review ratting
SELECT itempurchased, AVG(reviewrating) AS average_product_rating
FROM customer
GROUP BY itempurchased
ORDER BY AVG(reviewrating)
LIMIT 5;
--q4 compare the average purchase amount between standard and express shipping 
select shippingtype ,
Round(AVG ("purchaseamount(usd)"),2)
from  customer
where shippingtype in ('Standard','Express')
group by shippingtype 
--q5 Do subscribed customers spend more? compare?
select subscriptionstatus,
count(customerid)as totalcustomer, 
ROUND(AVG("purchaseamount(usd)"),2)as avg_spend,
ROUND(SUM("purchaseamount(usd)"),2)as totalrevenue
from customer
group by subscriptionstatus
order by totalrevenue,avg_spend desc;
--q6 which 5 product have the hishest precentage of purchase with dicount applied?
SELECT itempurchased,
       ROUND(
         SUM(CASE WHEN discountapplied = 'YES' THEN 1 ELSE 0 END) * 100.0
         / COUNT(*)
       , 2) AS discountrate
FROM customer
GROUP BY itempurchased
ORDER BY discountrate DESC;
--q7 what are the top 3 most purchased product each catagory??
WITH itemcounts AS (
    SELECT 
        category,
        itempurchased,
        COUNT(customerid) AS totalorders,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customerid) DESC) AS itemrank
    FROM customer
    GROUP BY category, itempurchased
)
SELECT 
    itemrank,
    category,
    itempurchased,
    totalorders
FROM itemcounts
WHERE itemrank <= 3;
--q8 ARE customers who are reuest buyres also likely to subscribe?
select Subscriptionstatus ,
count (customerid) as reapeatbuyers
from customer
where previouspurchases >5
group by subscriptionstatus 
--q9 what is the revenue contributen of each age group?
select age_group,
SUM("purchaseamount(usd)")as totalrevenue
FROM customer
GROUP BY age_group
ORDER BY totalrevenue desc;

